name: Ingest # Workflow name shown in the Actions tab

# Trigger event
on:
  workflow_dispatch: # Manual trigger (run it by hand from the UI)

permissions:
  id-token: write # Required to request the OIDC token for AWS
  contents: read # Read-only access to the repo code

# The job to be run
jobs:
  ingest:
    runs-on: ubuntu-latest # Runner (VM) where the job executes

    steps:
        # first step: checkout the repo code into the runner
      - name: Checkout
        uses: actions/checkout@v4 # Pull the repo code into the runner
        
        # second step: configure AWS credentials using OIDC
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }} # IAM role to assume via OIDC
          aws-region: us-east-2 # AWS region for all calls
        
        # third step: build the ingestion Docker image
      - name: Build ingestion image
        run: docker build -f pipelines/ingestion/Dockerfile -t anybuddy-ingestion . # Build the image from the Dockerfile

        # Run the ingestion Docker image
      - name: Run ingestion
        run: |
          docker run --rm \
            -e AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY \
            -e AWS_SESSION_TOKEN \
            -e APP_ENV=production \
            -e AWS_REGION=us-east-2 \
            -e S3_BUCKET=anybuddy-artifacts \
            -e KNOWLEDGE_S3_KEY=knowledge_base/faqs.txt \
            -e EMBEDDING_MODEL_S3_KEY=models/embedding_model.tar.gz \
            -e VECTOR_DB_S3_BUCKET=anybuddy-artifacts \
            -e VECTOR_DB_S3_PREFIX=vector_db \
            anybuddy-ingestion